"""initial schema

Revision ID: 22fd0f9f3fa4
Revises: 
Create Date: 2025-12-29 20:40:47.441217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22fd0f9f3fa4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_payment_id'), ['payment_id'], unique=False)

    with op.batch_alter_table('payment_request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_request_cliente'), ['cliente'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_request_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_request_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_request_medio_pago'), ['medio_pago'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_request_sucursal'), ['sucursal'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_request_telegram_user_id'), ['telegram_user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_request_telegram_user_id'))
        batch_op.drop_index(batch_op.f('ix_payment_request_sucursal'))
        batch_op.drop_index(batch_op.f('ix_payment_request_medio_pago'))
        batch_op.drop_index(batch_op.f('ix_payment_request_estado'))
        batch_op.drop_index(batch_op.f('ix_payment_request_created_at'))
        batch_op.drop_index(batch_op.f('ix_payment_request_cliente'))

    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_payment_id'))

    # ### end Alembic commands ###
