"""add fecha_consignacion to payment_request

Revision ID: 48a592c9d267
Revises: b8ecd890c7a8
Create Date: 2025-12-29 22:09:02.135132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48a592c9d267'
down_revision = 'b8ecd890c7a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_consignacion', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_request', schema=None) as batch_op:
        batch_op.drop_column('fecha_consignacion')

    # ### end Alembic commands ###
