"""add sociedad to payment_request

Revision ID: b8ecd890c7a8
Revises: c06d29e9a285
Create Date: 2025-12-29 21:55:18.320458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8ecd890c7a8'
down_revision = 'c06d29e9a285'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sociedad', sa.Enum('COANDES', 'MANCHESTER', 'ALMACENES', name='sociedad'), nullable=True))
        batch_op.create_index(batch_op.f('ix_payment_request_sociedad'), ['sociedad'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_request_sociedad'))
        batch_op.drop_column('sociedad')

    # ### end Alembic commands ###
