"""add sociedad to whitelist

Revision ID: c06d29e9a285
Revises: fbcf5e028b2c
Create Date: 2025-12-29 21:40:21.395001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c06d29e9a285'
down_revision = 'fbcf5e028b2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reporter_whitelist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sociedad', sa.Enum('COANDES', 'MANCHESTER', 'ALMACENES', name='sociedad'), nullable=True))
        batch_op.create_index(batch_op.f('ix_reporter_whitelist_sociedad'), ['sociedad'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reporter_whitelist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reporter_whitelist_sociedad'))
        batch_op.drop_column('sociedad')

    # ### end Alembic commands ###
