"""baseline + indexes

Revision ID: fbcf5e028b2c
Revises: 22fd0f9f3fa4
Create Date: 2025-12-29 21:12:00.003288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbcf5e028b2c'
down_revision = '22fd0f9f3fa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_request_valor'), ['valor'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_request_valor'))

    # ### end Alembic commands ###
